// 2025-26 Premiership Rugby inbound transfers.
//
// Source: https://en.wikipedia.org/wiki/List_of_2025-26_Premiership_Rugby_transfers
// Generated by scripts/auditTransfers2025_26.ts against the seeded
// rosters in src/data/team-*.json — 132 Wikipedia "In" entries
// processed, 101 name-matched (94 exact + 1 diacritic-stripped + 6
// last-name-fuzzy with first-name verification), 1 reject (Bryn vs
// Bryce Gordon are different players), 1 duplicate skip (Cammy
// Hutchison's permanent move + later loan), leaving 99 entries.
//
// 31 Wikipedia entries unmatched and skipped — these are players
// arriving from foreign leagues / lower divisions / short-term loans
// who aren't carried in the seeded roster, so there's nothing in
// state.career.roster to unwind. Examples: Hamish Watson (Edinburgh
// loan), Henry Mountford (former Leicester, didn't carry over),
// Marlon Farouk-Roy, Patrick Hogg, Tietie Tuimauga (Montauban).
//
// When the user picks Squad Builder at game start, every name here
// is matched against the seeded roster, removed from their current
// club, and added to state.career.freeAgents — giving the player a
// re-shaped pre-season pool to sign from. Name match key is the full
// name as it appears in the roster (firstName + ' ' + lastName),
// which is unique league-wide (CLAUDE.md § "Team data").
// `fromClub` is descriptive only — surfaced in the UI as context.

export interface PreSeasonTransfer {
  name: string;
  fromClub?: string;
}

export const PRE_SEASON_TRANSFERS_2025_26: PreSeasonTransfer[] = [
  // Bath
  { name: 'Dan Frost',              fromClub: 'Exeter Chiefs' },
  { name: 'Bernard van der Linde',  fromClub: 'Bulls' },
  { name: 'Santi Carreras',         fromClub: 'Gloucester' },
  { name: 'Henry Arundell',         fromClub: 'Racing 92' },
  { name: 'Chris Harris',           fromClub: 'Gloucester' },
  // Bristol Bears
  { name: 'Tom Jordan',             fromClub: 'Glasgow Warriors' },
  { name: 'Pedro Rubiolo',          fromClub: 'Newcastle Red Bulls' },
  { name: 'Max Pepper',             fromClub: 'Newcastle Red Bulls' },
  { name: 'Josh Carrington',        fromClub: 'Cardiff Metropolitan University' },
  { name: 'Will Ramply',            fromClub: 'University of Nottingham' },
  { name: 'Luka Ivanishvili',       fromClub: 'Black Lion' },
  { name: 'Louis Rees-Zammit',      fromClub: 'Jacksonville Jaguars (NFL)' },
  // Exeter Chiefs
  { name: 'Tom Hooper',             fromClub: 'ACT Brumbies' },
  { name: 'Joseph Dweba',           fromClub: 'Stormers' },
  { name: 'Stephen Varney',         fromClub: 'Vannes' },
  { name: 'Julian Heaven',          fromClub: 'NSW Waratahs' },
  { name: 'Charlie Chapman',        fromClub: 'Gloucester' },
  { name: 'Len Ikitau',             fromClub: 'ACT Brumbies' },
  { name: 'Andrea Zambonin',        fromClub: 'Zebre Parma' },
  { name: 'Bachuki Tchumbadze',     fromClub: 'Black Lion' },
  { name: 'Khwezi Mona',            fromClub: 'Sharks' },
  // Gloucester
  { name: 'Will Joseph',            fromClub: 'Harlequins' },
  { name: 'Ross Byrne',             fromClub: 'Leinster' },
  { name: 'Ben Loader',             fromClub: 'Stormers' },
  { name: 'James Venter',           fromClub: 'Sharks' },
  { name: 'Jack Innard',            fromClub: 'Exeter Chiefs' },
  { name: 'Ben Redshaw',            fromClub: 'Newcastle Red Bulls' },
  { name: 'Jack Mann',              fromClub: 'Glasgow Warriors' },
  { name: 'Will Trenholm',          fromClub: 'Harlequins' },
  { name: 'Mike Austin',            fromClub: 'Hartpury University' },
  { name: 'Josh Basham',            fromClub: 'Shimizu Koto Blue Sharks' },
  { name: 'Hugh Bokenham',          fromClub: 'Cornish Pirates' },
  { name: 'Rob Russell',            fromClub: 'Leinster' },
  { name: 'Nepo Laulala',           fromClub: 'Toulouse' },
  { name: 'Jono Benz-Salomon',      fromClub: 'Hartpury University' },
  { name: 'Danny Eite',             fromClub: 'Academy (promoted)' },
  { name: 'Afolabi Fasogbon',       fromClub: 'Academy (promoted)' },
  { name: 'Josh Hathaway',          fromClub: 'Academy (promoted)' },
  { name: 'Archie McArthur',        fromClub: 'Academy (promoted)' },
  // Harlequins
  { name: 'Kieran Treadwell',       fromClub: 'Ulster' },
  { name: 'Guido Petti',            fromClub: 'Bordeaux' },
  { name: 'Harry Williams',         fromClub: 'Pau' },
  { name: 'George Turner',          fromClub: 'Kobelco Kobe Steelers' },
  { name: 'Stu Townsend',           fromClub: 'Exeter Chiefs' },
  { name: 'Max Green',              fromClub: 'Périgueux' },
  { name: 'Boris Wenger',           fromClub: 'Dogos' },
  { name: 'Pedro Delgado',          fromClub: 'Dogos' },
  { name: 'Sean Kerr',              fromClub: 'Academy (promoted)' },
  // Leicester Tigers
  { name: 'Jamie Blamire',          fromClub: 'Newcastle Red Bulls' },
  { name: 'Tarek Haffar',           fromClub: 'Northampton Saints' },
  { name: 'Wilf McCarthy',          fromClub: 'Hartpury University' },
  { name: 'Joaquin Moro',           fromClub: 'Pampas XV' },
  { name: 'Charlie Titcombe',       fromClub: 'Scarlets' },
  { name: 'Ollie Allan',            fromClub: 'Academy (promoted)' },
  { name: 'Lewis Chessum',          fromClub: 'Academy (promoted)' },
  { name: 'Archie van der Flier',   fromClub: 'Academy (promoted)' },
  { name: 'Joshua Manz',            fromClub: 'Academy (promoted)' },
  { name: 'Cameron Miell',          fromClub: 'Academy (promoted)' },
  { name: 'Orlando Bailey',         fromClub: 'Bath' },
  { name: 'Gabriel Hamer-Webb',     fromClub: 'Cardiff' },
  { name: "James O'Connor",         fromClub: 'Crusaders' },
  { name: 'Billy Searle',           fromClub: 'Agen' },
  { name: 'John Stewart',           fromClub: 'Bath' },
  { name: 'James Thompson',         fromClub: 'Chiefs (NZ)' },
  { name: 'Tonga Kofe',             fromClub: 'Utah Warriors' },
  // Newcastle Red Bulls
  { name: 'Ethan Grayson',          fromClub: 'San Diego Legion' },
  { name: 'Connor Doherty',         fromClub: 'Sale Sharks' },
  { name: 'George McGuigan',        fromClub: 'Ospreys' },
  { name: 'Jamie Hodgson',          fromClub: 'Edinburgh' },
  { name: 'Freddie Clarke',         fromClub: 'Gloucester' },
  { name: 'Amanaki Mafi',           fromClub: 'Yokohama Canon Eagles' },
  { name: 'Simon Benitez Cruz',     fromClub: 'Tarucas' },
  { name: 'Tom Christie',           fromClub: 'Crusaders' },
  { name: 'Fergus Lee-Warner',      fromClub: 'NSW Waratahs' },
  { name: 'Boeta Chamberlain',      fromClub: 'Bulls' },
  { name: 'Hame Faiva',             fromClub: 'Bath' },
  { name: 'Christian Wade',         fromClub: 'Wigan Warriors (Rugby League)' },
  { name: 'Joel Grayson',           fromClub: 'Old Northamptonians' },
  { name: 'Harrison Obatoyinbo',    fromClub: 'Mont-de-Marsan' },
  { name: 'Sam Waugh',              fromClub: 'Loughborough Students' },
  { name: 'Liam Williams',          fromClub: 'Saracens' },
  { name: 'Cameron Hutchison',      fromClub: 'Saracens' },
  { name: 'Samson Adejimi',         fromClub: 'Saracens (season-long loan)' },
  // Northampton Saints
  { name: 'Cleopas Kundiona',       fromClub: 'Nevers' },
  { name: 'Amena Caqusau',          fromClub: 'Glasgow Warriors' },
  { name: 'Danilo Fischetti',       fromClub: 'Zebre Parma' },
  { name: 'Callum Chick',           fromClub: 'Newcastle Red Bulls' },
  { name: 'Anthony Belleau',        fromClub: 'Clermont' },
  { name: 'JJ van der Mescht',      fromClub: 'Stade Français' },
  { name: 'James Martin',           fromClub: 'Coventry' },
  { name: 'Aiden Pugh',             fromClub: 'Bath' },
  // Sale Sharks
  { name: 'Nathan Jibulu',          fromClub: 'Harlequins' },
  { name: 'Marius Louw',            fromClub: 'Lions' },
  { name: 'Jacques Vermeulen',      fromClub: 'Exeter Chiefs' },
  { name: 'Reuben Logan',           fromClub: 'Northampton Saints' },
  // Saracens
  { name: 'Max Malins',             fromClub: 'Bristol Bears' },
  { name: 'Marcus Street',          fromClub: 'Exeter Chiefs' },
  { name: 'Vilikesa Nairau',        fromClub: 'Coventry' },
  { name: 'Owen Farrell',           fromClub: 'Racing 92' },
];
